
remote_theme: pages-themes/minimal@v0.2.0
plugins:
  - jekyll-remote-theme
title: Jane Doe
description: Personal website of Jane Doe, showcasing professional achievements, projects, and contact information.
show_downloads: false
google_analytics: "" # Add your Google Analytics Tracking ID here if you have one
author: Jane Doe
email: jane.doe@email.com
linkedin_username: janedoe
github_username: janedoe